
spring:
  application:
    name: server8762
server:
  port: 8762
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true

    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
