
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
      prefer-ip-address:  true
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: eureka-provider
server:
  port: 9089