eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: eureka-customer
server:
  port: 8082

#feign:
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false
feign:
  hystrix:
    enabled: true